# Generated by Django 4.2.4 on 2024-02-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sensor', models.CharField(max_length=100)),
                ('minimum_illumination', models.CharField(max_length=100)),
                ('shutter_speed', models.CharField(max_length=100)),
                ('lens', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('day_night', models.CharField(max_length=100)),
                ('dnr', models.CharField(max_length=100)),
                ('night_vision', models.CharField(max_length=100)),
                ('local_storage', models.CharField(help_text='Supports microSD card (Up to 256G) on the pairing base station', max_length=100)),
                ('cloud_storage', models.CharField(help_text='Supports EZVIZ CloudPlay storage (subscription required)', max_length=100)),
                ('power_supply_camera', models.CharField(max_length=100)),
                ('power_supply_base', models.CharField(max_length=100)),
                ('power_consumption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_resolution', models.CharField(max_length=100)),
                ('frame_rate', models.CharField(max_length=100)),
                ('video_compression', models.CharField(max_length=100)),
                ('video_bit_rate', models.CharField(max_length=100)),
                ('audio_bit_rate', models.CharField(max_length=100)),
                ('max_bitrate', models.CharField(max_length=100)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_standard', models.CharField(max_length=100)),
                ('frequency_range_us', models.CharField(max_length=100)),
                ('frequency_range_eu', models.CharField(max_length=100)),
                ('channel_bandwidth_us', models.CharField(max_length=100)),
                ('channel_bandwidth_eu', models.CharField(max_length=100)),
                ('security', models.CharField(max_length=100)),
                ('wifi_ha_low_pairing', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('interface_protocol', models.CharField(max_length=100)),
                ('minimum_network_requirement', models.CharField(max_length=100)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specification')),
            ],
        ),
        migrations.CreateModel(
            name='InTheBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='inventory.item')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specification')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_conditions_temperature', models.CharField(max_length=100)),
                ('operating_conditions_humidity', models.CharField(max_length=100)),
                ('ip_grade', models.CharField(max_length=10)),
                ('package_dimensions', models.CharField(max_length=100)),
                ('weight_camera', models.CharField(max_length=100)),
                ('weight_base', models.CharField(max_length=100)),
                ('weight_with_package', models.CharField(max_length=100)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='inventory.camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='certifications',
            field=models.ManyToManyField(to='inventory.certification'),
        ),
        migrations.AddField(
            model_name='camera',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specification'),
        ),
    ]
