# Generated by Django 4.2.4 on 2024-02-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specification',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='specification',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='inthebox',
            old_name='specification',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='specification',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='videoaudio',
            old_name='specification',
            new_name='model',
        ),
    ]
