# Generated by Django 4.2.4 on 2024-02-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_specification_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.model'),
        ),
    ]
