# Generated by Django 4.2.4 on 2024-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_images/'),
        ),
    ]
