# Generated by Django 4.2.4 on 2024-02-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='camera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_camera', to='inventory.camera'),
        ),
    ]
