# Generated by Django 5.0.1 on 2024-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_model_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
