# Generated by Django 5.0.1 on 2024-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_model_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('electronic', 'Electronic'), ('clothing', 'Clothing'), ('furniture', 'Furniture')], max_length=20, null=True),
        ),
    ]
