# Generated by Django 4.2.4 on 2024-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_general_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cloud_storage',
            field=models.CharField(blank=True, help_text='Supports EZVIZ CloudPlay storage (subscription required)', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='day_night',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='dnr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='image_sensor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='lens',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='local_storage',
            field=models.CharField(blank=True, help_text='Supports microSD card (Up to 256G) on the pairing base station', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='minimum_illumination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='night_vision',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='power_consumption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='power_supply_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='power_supply_camera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='ip_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='general',
            name='operating_conditions_humidity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='operating_conditions_temperature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='package_dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='weight_base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='weight_camera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='weight_with_package',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='channel_bandwidth_eu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='channel_bandwidth_us',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='frequency_range_eu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='frequency_range_us',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='interface_protocol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='minimum_network_requirement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='protocol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='security',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='wifi_ha_low_pairing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='wifi_standard',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='audio_bit_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='frame_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='max_bitrate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='max_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='video_bit_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoaudio',
            name='video_compression',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
