# Generated by Django 5.0.1 on 2024-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='specifications',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model_image',
        ),
        migrations.AddField(
            model_name='item',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('wire-free cameras', 'Wire-Free Cameras'), ('indoor wi-Fi cameras', 'Indoor Wi-Fi Cameras'), ('outdoor wi-Fi cameras', 'Outdoor Wi-Fi Cameras')], max_length=100, null=True),
        ),
    ]
