# Generated by Django 4.2.4 on 2024-02-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_newslettersubscriber_alter_camera_cloud_storage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
