# Generated by Django 4.2.4 on 2024-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_delete_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('wire', 'Wire'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='wire', max_length=100),
        ),
    ]
